version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true" #disable https and logins
      compatibility.override_main_response_version: "true"
      network.host: "0.0.0.0"
    ports:
      - "9200:9200"
      - "9600:9600" # required for performance Analyzer

    # console at http://localhost:5610/app/dev_tools#/console
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      network.host: "0.0.0.0"
